common/programmers/가장 큰 수/가장 큰 수_변준우.java, common/programmers/가장 큰 수/가장 큰 수_변준우_최적화.java
* https://school.programmers.co.kr/learn/courses/30/lessons/42746
* StringBuilder 사용 필수로 보임
* 최적화 버전은 원본 작성 후 메모리/소요시간 확인 뒤 재작성
=> movebxeax:: programmers 가장 큰 수_변준우.java 추가

common/programmers/피로도/피로도_변준우.java
* https://school.programmers.co.kr/learn/courses/30/lessons/87946
* 특이사항 없음
=> movebxeax:: programmers 피로도_변준우.java 추가

common/programmers/큰 수 만들기/큰 수 만들기_이혜지.java
```
stack 비어있으면 넣어주고 다음꺼 진행
if 이전 요소가 현재요소보다 크다면
넣어준다
하지만 이전 요소가 현재요소보다 작다면
스택에서 빼주고 k-- 그리고 현재 요소 넣어준다. 
k가 0이 될때까지
```
=> leehyeji319:: 큰 수 만들기 추가

.gitignore, common/programmers/피로도/피로도_오종석.java
=> jongseok-oh::피로도 추가

common/programmers/큰 수 만들기/큰 수 만들기.java
=> jongsoek-oh::큰 수 만들기 추가

jongseok-oh/programmers/조이스틱.java
=> jongseok-oh::조이스틱 추가

common/programmers/피로도/피로도_강효진.java
`if (k < dungeons[i][0]) {
continue;
}`
이 부분에서 헤맸음
=> KanHyojin1401:: programmers 피로도_강효진.java 추가

common/programmers/타겟 넘버/타겟 넘버_변준우.java
* https://school.programmers.co.kr/learn/courses/30/lessons/43165
=> movebxeax:: 타겟 넘버_변준우.java 추가

common/programmers/다리를 지나는 트럭/다리를 지나는 트럭_변준우.java
* https://school.programmers.co.kr/learn/courses/30/lessons/42583
=> movebxeax:: 다리를 지나는 트럭_변준우.java 추가

common/programmers/타겟 넘버/타겟 넘버.java
=> jongseok-oh::타겟 넘버.java 추가

common/programmers/타겟 넘버/타겟넘버_이혜지.java
bfs
테케 {1,1,1,1,1} 로 봤을 때,
이럿게 하면 [5, 3, 3, 1, 3, 1, 1, -1, 3, 1, 1, -1, 1, -1, -1, -3, 3, 1, 1, -1, 1, -1, -1, -3, 1, -1, -1, -3, -1, -3, -3, -5] 이렇게 배열이 나옴 이중에 돌면서 target의 cnt++ 해줌
먼저 super node로 [0]을 하나 만들어 두고 
[0+1] [0-1] 로 sub node 두개를 생성
이렇게 생성된노드 super node로 저장, 
저장된 super node는 for문을 돌면서 [0+1+1] [0+1-1] , [0-1+1] [0-1-1] 를 거치면서 super node에 다시 저장.
=> leehyeji319::타겟넘버 추가

common/programmers/다리를 지나는 트럭/다리를 지나는 트럭_오종석.java
=> jongseok-oh::다리를 지나는 트럭.java 추가

common/programmers/타겟 넘버/타겟 넘버_강효진.java
=> KangHyojin1401:: programmers 타겟 넘버_강효진.java 추가

common/programmers/여행경로/여행경로_변준우.java
* https://school.programmers.co.kr/learn/courses/30/lessons/43164
=> movebxeax:: programmers 여행경로_변준우.java 추가

common/programmers/단어 변환/단어 변환_변준우.java
* https://school.programmers.co.kr/learn/courses/30/lessons/43163
=> movebxeax:: programmers 단어 변환_변준우.java 추가

common/programmers/여행경로/여행경로_오종석.java
=> jongseok-oh::여행경로_오종석java 추가

common/programmers/단어 변환/단어 변환_오종석.java
=> jongseok-oh::단어 변환_오종석.java 추가

common/programmers/더 맵게/더 맵게_변준우.java
* https://school.programmers.co.kr/learn/courses/30/lessons/42626
=> movebxeax:: programmers 더 맵게_변준우.java 추가

common/programmers/입국심사/입국심사_변준우.java, common/programmers/입국심사/입국심사_변준우_stream.java
* https://school.programmers.co.kr/learn/courses/30/lessons/43238
=> movebxeax:: programmers 입국심사_변준우.java 추가

common/programmers/입국심사/입국심사_오종석.java
=> jongseok-oh::입국심사_오종석.java 추가

common/programmers/퍼즐 조각 채우기/퍼즐 조각 채우기_오종석.java
=> jongseok-oh::퍼즐 조각 채우기_오종석.java 추가

common/boj/뱀/3190_뱀_이윤환.java
https://www.acmicpc.net/problem/3190
=> unannn:: boj 3190_뱀_이윤환.java  추가

common/boj/3190_변준우.cpp, common/boj/3190_변준우.java
* https://www.acmicpc.net/problem/3190
=> movebxeax:: boj 3190_뱀_변준우.java 추가

common/boj/14499/14499_주사위굴리기_이혜지.py
=> leehyeji319:: boj_14499_주사위굴리기_이혜지.py 추가

9jinseok/boj/청소년상어.java
https://www.acmicpc.net/problem/19236
=> 9jinseok:: boj 청소년상어.java 추가

9jinseok/boj/감시.java
https://www.acmicpc.net/problem/15683
=> 9jinseok:: boj 감시.java 추가

common/boj/14499/14499_주사위굴리기_이윤환.java
https://www.acmicpc.net/problem/14499
=> unannn::boj 14499_주사위굴리기_이윤환.java 추가

common/boj/20058/20058_마법사상어와파이어스톰_이윤환.java
https://www.acmicpc.net/problem/20058
=> unannn:: boj 20058_마법사상어와파이어스톰_이윤환.java 추가

common/boj/3190/3190_오종석.cpp
=> jongseok-oh::3190_오종석.cpp 추가

common/boj/14499/14499_주사위굴리기_오종석.cpp
=> jongseok-oh::boj 14499 추가

common/boj/20058/20058_마법사 상어와 파이어스톰_오종석.cpp
=> jongseok-oh::20058_마법사 상어와 파이어스톰_오종석.cpp 추가

common/boj/14499/14499_주사위굴리기_변준우.cpp
* https://www.acmicpc.net/problem/14499
=> movebxeax:: boj 14499_주사위굴리기_변준우.cpp 추가

common/boj/20058/20058_마법사상어와파이어스톰_변준우.cpp
* https://www.acmicpc.net/problem/20058
=> movebxeax:: boj 20058_마법사상어와파이어스톰_변준우.cpp 추가

movebxeax/boj/19236/19236_청소년상어_변준우.cpp
* https://www.acmicpc.net/problem/19236
=> movebxeax:: boj 19236_청소년상어_변준우.cpp 추가

movebxeax/boj/17144/17144_미세먼지안녕_변준우.cpp
* https://www.acmicpc.net/problem/17144
=> movebxeax:: boj 17144_미세먼지안녕_변준우.cpp 추가

movebxeax/boj/15683/15683_감시_변준우.cpp
* https://www.acmicpc.net/problem/15683
=> movebxeax:: boj 15683_감시_변준우.cpp 추가

movebxeax/boj/16236/16236_아기상어_변준우.cpp
* https://www.acmicpc.net/problem/16236
=> movebxeax:: boj 16236_아기상어_변준우.cpp 추가

movebxeax/boj/17143/17143_낚시왕_변준우.cpp
* https://www.acmicpc.net/problem/17143
=> movebxeax:: boj 17143_낚시왕_변준우.cpp 추가

movebxeax/boj/5430_변준우.java
* https://www.acmicpc.net/problem/5430
=> movebxeax:: BOJ 5430_변준우.java 추가

9jinseok/boj/구슬탈출2.java
https://www.acmicpc.net/problem/13460
가능한 모든 경우 다 하면 4^10이라 좀 빡센데 가지치기해서 시간 절약 ( 840ms > 340ms )
근데 다른 사람들 시간 보면 100언저리라 이런 쌩완탐말고 다른 방법이 있는 듯
=> 9jinseok:: boj 구슬탈출2.java 추가

common/swea/15173_Shuffle-O-Matic.cpp
=> jongseok-oh::15173_Shuffle-O-Matic.cpp 추가

common/swea/낚시터자리잡기/낚시터자리잡기_이혜지.py, leehyeji319/swea/낚시터자리잡기/낚시터자리잡기_이혜지_시간초과실패.py
https://swexpertacademy.com/main/talk/codeBattle/problemDetail.do?contestProbId=AYLNTUm6AswDFASv&categoryId=AYLNSmY6An0DFASv&categoryType=BATTLE&battleMainPageIndex=1
=> leehyeji319:: swea_낚시터자리잡기_이혜지.py 추가

common/swea/헌터/헌터_이혜지.py
https://swexpertacademy.com/main/talk/codeBattle/problemDetail.do?contestProbId=AYLNULBaAyQDFASv&categoryId=AYLNSmY6An0DFASv&categoryType=BATTLE&battleMainPageIndex=1
=> leehyeji319:: swea_헌터_이혜지.py 추가

leehyeji319/boj/17281/17281_야구_이혜지.py
https://www.acmicpc.net/problem/17281
=> leehyeji319:: boj_17281_야구_이혜지.py 추가

leehyeji319/boj/17471/17471_게리멘더링_이혜지.py
https://www.acmicpc.net/problem/17471
=> leehyeji319:: boj_17471_게리멘더링_이혜지.py 추가

movebxeax/boj/17281/17281_야구_변준우.cpp
* https://www.acmicpc.net/problem/17281
=> movebxeax:: boj 17281_야구_변준우.cpp 추가

common/boj/20056/20056_마법사 상어와 파이어볼.cpp
=> jongseok-oh::boj_20056_마법사 상어와 파이어볼.cpp 추가

unannn/boj/1504/1504_특정한최단경로_이윤환.java
https://www.acmicpc.net/problem/1504
=> unannn:: boj 1504_특정한최단경로_이윤환.java 추가

movebxeax/boj/17471/17471_게리멘더링_변준우.cpp
* https://www.acmicpc.net/problem/17471
=> movebxeax:: boj 17471_게리멘더링_변준우.cpp 추가

movebxeax/boj/14502/14502_연구소_변준우.cpp
* https://www.acmicpc.net/problem/14502
=> movebxeax:: boj 14502_연구소_변준우.cpp 추가

common/boj/20056/20056_마법사상어와파이어볼_변준우.cpp
* https://www.acmicpc.net/problem/20056
=> movebxeax:: boj 20056_마법사상어와파이어볼_변준우.cpp 추가

unannn/boj/1806/1806_부분합_이윤환.java
https://www.acmicpc.net/problem/1806
=> unannn:: boj 1806_부분합_이윤환.java 추가

movebxeax/boj/16637/16637_괄호추가하기_변준우.cpp
* https://www.acmicpc.net/problem/16637
=> movebxeax:: boj 16637_괄호추가하기_변준우.cpp 추가

movebxeax/boj/19238/19238_스타트택시_변준우.cpp
* https://www.acmicpc.net/problem/19238
=> movebxeax:: boj 19238_스타트택시_변준우.cpp 추가

common/programmers/파괴되지않은건물/파괴되지않은건물_오종석.cpp
=> jongseok-oh::파괴되지않은건물_오종석.cpp 추가

common/programmers/신고결과받기/신고결과받기_이혜지.py
https://school.programmers.co.kr/learn/courses/30/lessons/92334
=> leehyeji319:: programmers 신고결과받기_이혜지.py 추가

common/programmers/k진수에서소수개수구하기/k진수에서소수개수구하기_이혜지.py
https://school.programmers.co.kr/learn/courses/30/lessons/92335
=> leehyeji319:: programmers k진수에서소수개수구하기_이혜지.py

common/programmers/주차요금계산/주차요금계산_이혜지.py
https://school.programmers.co.kr/learn/courses/30/lessons/92341
=> leehyeji319:: programmers 주차요금계산_이혜지.py 추가

common/programmers/양궁대회/양궁대회_이혜지.py
https://school.programmers.co.kr/learn/courses/30/lessons/92342
=> leehyeji319:: programmers 양궁대회_이혜지.py 추가

common/programmers/주차요금계산/주차요금계산_이윤환.java
https://school.programmers.co.kr/learn/courses/30/lessons/92341
=> unannn:: programmers 주차요금계산_이윤환.java 추가

unannn/programmers/양궁대회/양궁대회_이윤환.java
https://school.programmers.co.kr/learn/courses/30/lessons/92342
=> unannn:: programmers 양궁대회_이윤환.java 추가

common/programmers/양과늑대/양과늑대_이윤환.java
https://school.programmers.co.kr/learn/courses/30/lessons/92343
=> unannn:: programmers 양과늑대_이윤환.java 추가

unannn/boj/17425/17425_약수의합_이윤환.java
https://www.acmicpc.net/problem/17425
=> unannn:: boj 17425_약수의합_이윤환.java 추가

unannn/boj/3020/3020_개똥벌레_이윤환.java
https://www.acmicpc.net/problem/3020
=> unannn:: boj 3020_개똥벌레_이윤환.java 추가

unannn/boj/21758/21758_꿀따기_이윤환.java
https://www.acmicpc.net/problem/21758
=> unannn:: boj 21758_꿀따기_이윤환.java 추가

common/programmers/신고결과받기/신고결과받기_변준우.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/92334
=> movebxeax:: programmers 신고결과받기_변준우.cpp 추가

common/programmers/K진수에서소수개수구하기/k진수에서소수개수구하기_변준우.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/92335
=> movebxeax:: programmers k진수에서소수개수구하기_변준우.cpp 추가

common/programmers/주차요금계산/주차요금계산_변준우.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/92341
=> movebxeax:: programmers 주차요금계산_변준우.cpp 추가

common/programmers/순위검색/순위검색_이윤환.java
https://school.programmers.co.kr/learn/courses/30/lessons/72412
=> unannn:: programmers 순위검색_이윤환.java 추가

common/programmers/메뉴리뉴얼/메뉴리뉴얼_변준우.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/72411
=> movebxeax:: programmers 메뉴리뉴얼_변준우.cpp 추가

common/programmers/신규아이디추천/신규아이디추천_강효진.java
테스트 1 〉 | 통과 (0.07ms, 76.7MB)
테스트 2 〉 | 통과 (0.07ms, 75.8MB)
테스트 3 〉 | 통과 (0.07ms, 72.1MB)
테스트 4 〉 | 통과 (0.06ms, 75.9MB)
테스트 5 〉 | 통과 (0.07ms, 77.8MB)
테스트 6 〉 | 통과 (0.06ms, 75.5MB)
테스트 7 〉 | 통과 (0.05ms, 75.3MB)
테스트 8 〉 | 통과 (0.06ms, 78.4MB)
테스트 9 〉 | 통과 (0.06ms, 64.3MB)
테스트 10 〉 | 통과 (0.04ms, 77.6MB)
테스트 11 〉 | 통과 (0.08ms, 72.3MB)
테스트 12 〉 | 통과 (0.10ms, 78.9MB)
테스트 13 〉 | 통과 (0.09ms, 67.1MB)
테스트 14 〉 | 통과 (0.09ms, 76.7MB)
테스트 15 〉 | 통과 (0.11ms, 70.3MB)
테스트 16 〉 | 통과 (0.15ms, 86.9MB)
테스트 17 〉 | 통과 (0.58ms, 80.8MB)
테스트 18 〉 | 통과 (0.83ms, 72.2MB)
테스트 19 〉 | 통과 (1.54ms, 71.3MB)
테스트 20 〉 | 통과 (0.63ms, 79.5MB)
테스트 21 〉 | 통과 (1.18ms, 73MB)
테스트 22 〉 | 통과 (0.82ms, 78.8MB)
테스트 23 〉 | 통과 (1.36ms, 75.5MB)
테스트 24 〉 | 통과 (1.24ms, 70.2MB)
테스트 25 〉 | 통과 (1.41ms, 75.3MB)
테스트 26 〉 | 통과 (1.02ms, 71MB)
=> KangHyojin1401:: programmers 신규아이디추천_강효진.java 추가

common/programmers/신규아이디추천/신규아이디추천_변준우.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/72410
=> movebxeax:: programmers 신규아이디추천_변준우.cpp 추가

common/programmers/메뉴리뉴얼/메뉴리뉴얼_이윤환.java
https://school.programmers.co.kr/learn/courses/30/lessons/72411
=> unannn:: programmers 메뉴리뉴얼_이윤환.java 추가

common/programmers/메뉴리뉴얼/메뉴리뉴얼_강효진.java
테스트 1 〉 | 통과 (11.76ms, 76.3MB)
테스트 2 〉 | 통과 (12.11ms, 80.5MB)
테스트 3 〉 | 통과 (14.02ms, 80MB)
테스트 4 〉 | 통과 (15.37ms, 76.3MB)
테스트 5 〉 | 통과 (13.95ms, 81.3MB)
테스트 6 〉 | 통과 (16.77ms, 79.3MB)
테스트 7 〉 | 통과 (16.10ms, 79.4MB)
테스트 8 〉 | 통과 (25.29ms, 78.6MB)
테스트 9 〉 | 통과 (25.94ms, 91.3MB)
테스트 10 〉 | 통과 (18.72ms, 81.2MB)
테스트 11 〉 | 통과 (18.35ms, 91.5MB)
테스트 12 〉 | 통과 (17.26ms, 78.1MB)
테스트 13 〉 | 통과 (25.20ms, 84MB)
테스트 14 〉 | 통과 (28.06ms, 84.7MB)
테스트 15 〉 | 통과 (23.82ms, 102MB)
테스트 16 〉 | 통과 (22.03ms, 87.8MB)
테스트 17 〉 | 통과 (28.65ms, 85.4MB)
테스트 18 〉 | 통과 (24.70ms, 89.2MB)
테스트 19 〉 | 통과 (18.46ms, 84.6MB)
테스트 20 〉 | 통과 (30.16ms, 81.2MB)
시간이 너무 오래 걸리는데 String +와 charAt() 때문인가?
=> KangHyojin1401:: programmers 메뉴리뉴얼_강효진.java 추가

common/boj/1916_최소비용구하기_강효진.java
백준 1916번 <최소비용 구하기>
[](https://www.acmicpc.net/problem/1916)
_주의사항_
1. w가 0도 가능!!!!!!! 그래서 간선 없는 경우를 0으로 두면 안 됨.
2. a->b 길이 여러개일 수있음
=> KangHyojin1401:: boj 1916 추가

common/boj/11779/11779_최소비용구하기2_변준우.cpp
* https://www.acmicpc.net/problem/11779
=> movebxeax:: boj 11779_최소비용구하기2_변준우.cpp 추가

unannn/boj/1717/1717_집합의표현_이윤환.java
=> unannn:: boj 1717_집합의표현_이윤환.java 추가

unannn/boj/1976/1976_여행가자_이윤환.java
=> unannn:: boj 1976_여행가자_이윤환.java 추가

common/boj/2307/2307_도로검문_변준우.cpp
* https://www.acmicpc.net/problem/2307
=> movebxeax:: boj 2307_도로검문_변준우.cpp 추가

common/boj/1916/1916_최소비용_변준우.cpp
* https://www.acmicpc.net/problem/1916
=> movebxeax:: boj 1916_최소비용_변준우.cpp 추가

unannn/boj/1922/1922_네트워크연결_이윤환.java
=> unannn:: boj 1922_네트워크연결_이윤환.java 추가

common/boj/19237/19237_어른상어_변준우.cpp
* https://www.acmicpc.net/problem/19237
=> movebxeax:: boj 19237_어른상어_변준우.cpp 추가

common/boj/15684/15684_사다리조작_변준우.cpp
* https://www.acmicpc.net/problem/15684
=> movebxeax:: boj 15684_사다리조작_변준우.cpp 추가

unannn/boj/4195/4195_친구네트워크_이윤환.java
=> unannn:: boj 4195_친구네트워크_이윤환.java 추가

common/boj/20057/20057_마법사상어와토네이도_변준우.cpp
* https://www.acmicpc.net/problem/20057
=> movebxeax:: boj 20057_마법사상어와토네이도_변준우.cpp 추가

common/boj/15684/15684_사다리조작_이혜지.py
https://www.acmicpc.net/problem/15684
=> leehyeji319:: boj 15684_사다리조작_이혜지.py 추가

movebxeax/boj/14725/14725_개미굴_변준우.cpp
* https://www.acmicpc.net/problem/14725
=> movebxeax:: boj 14725_개미굴_변준우.cpp 추가

common/boj/20057/20057_마법사상어와토네이도_이혜지.py
https://www.acmicpc.net/problem/20057
=> leehyeji319:: boj 20057_마법사상어와토네이도_이혜지.py 추가

movebxeax/boj/7432/7432_디스크트리_변준우.cpp
* https://www.acmicpc.net/problem/7432
=> movebxeax:: boj 7432_디스크트리_변준우.cpp 추가

unannn/boj/20040/20040_사이클게임_이윤환.java
=> unannn:: boj 20040_사이클게임_이윤환.java 추가

movebxeax/boj/11003/11003_최솟값찾기_변준우.cpp
* https://www.acmicpc.net/problem/11003
=> movebxeax:: boj 11003_최솟값찾기_변준우.cpp 추가

movebxeax/boj/2957/2957_이진탐색트리_변준우.cpp
* https://www.acmicpc.net/problem/2957
=> movebxeax:: boj 2957_이진탐색트리_변준우.cpp 추가

movebxeax/boj/5670/5670_휴대폰자판_변준우.cpp
* https://www.acmicpc.net/problem/5670
=> movebxeax:: boj 5670_휴대폰자판_변준우.cpp 추가

movebxeax/boj/5052/5052_전화번호목록_변준우.cpp
* https://www.acmicpc.net/problem/5052
=> movebxeax:: boj 5052_전화번호목록_변준우.cpp 추가

movebxeax/boj/5972/5972_택배배송_변준우.cpp
* https://www.acmicpc.net/problem/5972
=> movebxeax:: boj 5972_택배배송_변준우.cpp 추가

unannn/boj/2146/2146_다리만들기_이윤환.java
=> unannn:: boj 2146_다리만들기_이윤환.java 추가

movebxeax/boj/9251/9251_LCS_변준우.cpp
* https://www.acmicpc.net/problem/9251
=> movebxeax:: boj 9251_LCS_변준우.cpp 추가

movebxeax/boj/2325/2325_개코전쟁_변준우.cpp
* https://www.acmicpc.net/problem/2325
=> movebxeax:: boj 2325_개코전쟁_변준우.cpp 추가

common/boj/1991/1991_트리순회_이윤환.java
https://www.acmicpc.net/problem/1991
=> unannn:: boj 1991_트리순회_이윤환.java 추가

common/boj/1967/1967_트리의지름_이윤환.java
https://www.acmicpc.net/problem/1967
=> unannn:: boj 1967_트리의지름_이윤환.java 추가

common/boj/3020/3020_개똥벌레_이혜지.py
=> leehyeji319:: boj 3020_개똥벌레_이혜지.py 추가

common/boj/11660/11660_구간합구하기5_이윤환.java
https://www.acmicpc.net/problem/11660
=> unannn:: boj 11660_구간합구하기5_이윤환.java 추가

common/boj/5639/5639_이진검색트리_이윤환.java
https://www.acmicpc.net/problem/5639
=> unannn:: boj 5639_이진검색트리_이윤환.java 추가

common/boj/3020/3020_개똥벌레_변준우.cpp
* https://www.acmicpc.net/problem/3020
=> movebxeax:: boj 3020_개똥벌레_변준우.cpp 추가

common/boj/1167/1167_트리의지름_변준우.cpp
* https://www.acmicpc.net/problem/1167
=> movebxeax:: boj 1167_트리의지름_변준우.cpp 추가

common/boj/5639/5639_이진검색트리_변준우.cpp
* https://www.acmicpc.net/problem/5639
=> movebxeax:: boj 5639_이진검색트리_변준우.cpp 추가

common/boj/1967/1967_트리의지름_변준우.cpp
https://www.acmicpc.net/problem/1967
=> movebxeax:: boj 1967_트리의지름_변준우.cpp 추가

common/boj/13904/13904_과제_이혜지.py
=> leehyeji319:: boj 13904_과제_이혜지.py 추가

common/boj/7569/7569_토마토_이윤환.java
https://www.acmicpc.net/source/51363048
=> unannn:: boj 7569_토마토_이윤환.java 추가

common/boj/1991/1991_트리순회_변준우.cpp
* https://www.acmicpc.net/problem/1991
=> movebxeax:: boj 1991_트리순회_변준우.cpp 추가

common/boj/11725/11725_트리의부모찾기_변준우.cpp
* https://www.acmicpc.net/problem/11725
=> movebxeax:: boj 11725_트리의부모찾기_변준우.cpp 추가

movebxeax/boj/2056/2056_작업_변준우.cpp
* https://www.acmicpc.net/problem/2056
=> movebxeax:: boj 2056_작업_변준우.cpp 추가

unannn/boj/13305/13305_주유소_이윤환.java
https://www.acmicpc.net/problem/13305
=> unannn:: boj 13305_주유소_이윤환.java 추가

movebxeax/boj/1948/1948_임계경로_변준우.cpp
* https://www.acmicpc.net/problem/1948
=> movebxeax:: boj 1948_임계경로_변준우.cpp 추가

movebxeax/boj/1516/1516_게임개발_변준우.cpp
* https://www.acmicpc.net/problem/1516
=> movebxeax:: boj 1516_게임개발_변준우.cpp 추가

movebxeax/boj/1005/1005_ACMCraft_변준우.cpp
* https://www.acmicpc.net/problem/1005
=> movebxeax:: boj 1005_ACMCraft_변준우.cpp 추가

movebxeax/boj/2252/2252_줄세우기_변준우.cpp
* https://www.acmicpc.net/problem/2252
=> movebxeax:: boj 2252_줄세우기_변준우.cpp 추가

movebxeax/boj/1766/1766_문제집_변준우.cpp
* https://www.acmicpc.net/problem/1766
=> movebxeax:: boj 1766_문제집_변준우.cpp 추가

common/boj/13904/13904_과제_변준우.cpp
* https://www.acmicpc.net/problem/13904
=> movebxeax:: boj 13904_과제_변준우.cpp 추가

common/boj/11000/11000_강의실배정_변준우.cpp
* https://www.acmicpc.net/problem/11000
=> movebxeax:: boj 11000_강의실배정_변준우.cpp 추가

KangHyojin1401/boj/17135_캐슬디펜스_강효진.java
=> KangHyojin1401:: boj 17135_캐슬디펜스_강효진.java 추가

KangHyojin1401/boj/14501_퇴사_강효진.java
상담시간이 퇴사일을 넘어가면 continue 되게 했더니 실패 -> 이렇게 되면 아예 0이 되니까 이전까지의 최적해를 현재에 넣어줘야 함!!!
[https://www.acmicpc.net/board/view/85909](https://www.acmicpc.net/board/view/85909)
>dp[i] = dp[i + 1]이 없으면 dp의 일부 값이 갱신되지 않습니다.
=> KangHyojin1401:: boj 14501_퇴사_강효진.java 추가

movebxeax/boj/7576/7576_토마토_변준우.cpp
* https://www.acmicpc.net/problem/7576
=> movebxeax:: boj 7576_토마토_변준우.cpp 추가

KangHyojin1401/boj/13458_시험감독_강효진.java
- 실패 1 : 53번째 줄에 if (people > 0) 일 때를 안 넣어줬다. 즉, 총 감독관 한 명으로 커버 가능할 때 체크 안 해줌.
- 실패 2 : result를 int 형으로 해서 틀림.
>출력값이 최대로 될 때는 B와 C가 모두 1이고, N이 1,000,000이며 모든 A의 값들이 1,000,000일 때입니다. 
>이 경우, 답이 1,000,000,000,000으로 int 범위를 훨씬 넘습니다.
=> KangHyojin1401:: boj 13458_시험감독_강효진.java 추가
